//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinSan
    {
        public int SoSan { get; set; }
        public Nullable<int> GiaThue60Phut { get; set; }
        public Nullable<int> GiaThue90phut { get; set; }
        public string TinhTrang { get; set; }
    }
}
